from data.services.exceptions import UnknownError

LOG_IN__TOKEN_WAS_NOT_ENTERED = "Войти не удалось: токен не найден. Введите токен."

LOG_IN__INVALID_TOKEN = "Войти не удалось: неверный токен."

UNKNOWN_ERROR = "Что-то пошло не так"

LOG_IN__SUCCESSFUL = "Вход успешно выполнен"


BTN_AUTHORIZE = "Авторизоваться"


CLIENT_AUTHORIZE_STATE1_MSG = f"Для авторизации нажмите: '{BTN_AUTHORIZE}'"

CLIENT_AUTHORIZE_STATE1__USER_MISMATCH = "Это не твой контакт."
